### ISSUE TITLE
Please add CLI 751 data set

### ISSUE THREAD

**Issue by ikinter** [kpegion/COLA-DATASETS-CATALOG#106]
Please include in the COLA datasets catalog the data that students in CLIM 751 use for their semester project. This is a subset of the data from Huang et al. (2017) 60-year reforecast project. The data are on the COLA server:
/project/CLIM751/data
In 2 sub-directories: 
/project/CLIM751/data/monthly
/project/CLIM751/data/daily
Within each sub-directory, there is a separate directory for each of about 15-18 2D global gridded variables. The files are all netCDF (the monthly data have GrADS ctl files also in /project/CLIM751/data/monthly/ctl). Forecast ensembles (20 members) plus the reanalysis (obs) for each variable (member 21) are stored for all forecast times over 35 years.
Thank you.

**Comment by bnoushin7** [comment]
@ikinter @kpegion 
Thank you for creating the issue!
I do have a question.. How do you want them to be cataloged?
Do you want to have all [mld  prate  q850  soilw1  soilw2  soilw3  soilw4  sst  t2m  u200  u850  v200  v850  z200  z500  z700]
as sub-catalogs?
Thank you

**Comment by bnoushin7** [comment]
@ikinter @kpegion 
Would you also let me know what are the tags associated with them? Thank you

**Comment by kpegion** [comment]
@bnoushin7 @ikinter 
I will provide the tags and the info on sub catalogs after I take a look at the data. I'll get back to you about it, probably tomorrow.

**Comment by ikinter** [comment]
Dear Noushin - Please do make each variable (mld, prate, ...) a separate sub-catalog. I think Kathy is more knowledgeable about which tags would be appropriate. Thanks. -- Jim

**Comment by bnoushin7** [comment]
Dear Jim,
Thank you for your comment. I will start it as soon as Kathy gets back to me with Tags.
Thanks again
Noushin

**Comment by kpegion** [comment]
Hi @bnoushin7 I suggest that the catalog be in the following hierarchy for this

main
-> classes
    -> CLIM751
         -> monthly
             -> variables (e.g. slp, prate, etc.) each as their own subcatalog
         ->  daily
             -> variables (e.g. slp, prate, etc.) each as their own subcatalog

For tags, 
For all data use tags: gridded, model, global,refcst
use monthly tag for monthly data and daily tag for daily data


and for each variable use the following tags:
prate -> precip, atm
slp -> slp, atm
soilw2, soilw4, soilw1,soilw3 -> soil moisture, land
t2m -> temp, atm
u850,v850,u200,v200 -> wind, atm
z500,z200,z700 -> height, atm 
mld -> mld, ocn
q850-> humidity, atm
sst -> sst, ocn

For example, monthly sst tags would be [ gridded, model, global, refcst, monthly,  sst,  ocn]

Hopefully this makes sense.  Let me know if it doesn't.

**Comment by ikinter** [comment]
Thanks, Kathy!

****************************************************
Jim Kinter
Director, Center for Ocean-Land-Atmosphere Studies
Chair, Department of Atmospheric, Oceanic & Earth Sciences
Professor, Climate Dynamics
284 Research Hall, Mail Stop 6C5
George Mason University
4400 University Drive
Fairfax, VA 22030 USA
-------------------------------------------------------------------------------------------
tel: (703) 993-5700  *******  fax: (703) 993-5770
email: ikinter@gmu.edu<mailto:ikinter@gmu.edu> *** http://cola.gmu.edu<http://cola.gmu.edu/>
*****************************************************

**Comment by bnoushin7** [comment]
@kpegion Thanks a lot.
Here are my questions:
What do you mean by : 
main
--classes?

I mean where should I put them in the master (main) catalog? Who is the parent?

2- should I put the monthly , daily and sst under the monthly, daily, and sst that we already have or these are separate?
Thank you

**Comment by kpegion** [comment]
I drew a picture to show the catalog hierarchy (hopefully it shows up here properly). 

![Untitled Notebook (8)-2](https://user-images.githubusercontent.com/16332933/92187153-3c810100-ee16-11ea-8b70-649942db2312.jpg)

classes should be at the main catalog level (even with obs, reanalysis, analysis, model)
CLIM751 will be a sub-catalog under classes, then monthly and daily are sub-catalogs under CLIM751, then the variables are sub-catalogs under monthly and daily.

**Comment by bnoushin7** [comment]
Thank you so much!
It helped a lot.
Best regards
Noushin

**Comment by kpegion** [comment]
On https://kpegion.github.io/COLA-DATASETS-CATALOG/main

Change classes catalog description from:
_Data that students in CLIM 751 use for their semester project. This is a subset of the data from Huang et al. (2017) 60 yr re-forecast project._

to
_Data used in CLIM classes._

On https://kpegion.github.io/COLA-DATASETS-CATALOG/classes

Change sub-catalog clim_751 description to:
_Data that students in CLIM 751 use for their semester project. This is a subset of the data from Huang et al. (2017) 60 yr re-forecast project._

Link [Huang et al. (2017) 60 yr re-forecast] project to (https://doi.org/10.1175/JCLI-D-16-0642.1)

**Comment by kpegion** [comment]
@bnoushin7 is this issue resolved by PRs #116, #112 #110 #107

**Comment by bnoushin7** [comment]
@kpegion Yes. We can close it

**Comment by kpegion** [comment]
Resolved with PRs #116, #112 #110 #107
