### ISSUE TITLE
Name change

### ISSUE THREAD

**Issue by bnoushin7** [kpegion/COLA-DATASETS-CATALOG#109]
On https://kpegion.github.io/COLA-DATASETS-CATALOG/main

Change classes catalog description from:
Data that students in CLIM 751 use for their semester project. This is a subset of the data from Huang et al. (2017) 60 yr re-forecast project.

to
Data used in CLIM classes.

On https://kpegion.github.io/COLA-DATASETS-CATALOG/classes

Change sub-catalog clim_751 description to:
Data that students in CLIM 751 use for their semester project. This is a subset of the data from Huang et al. (2017) 60 yr re-forecast project.

Link [Huang et al. (2017) 60 yr re-forecast] project to (https://doi.org/10.1175/JCLI-D-16-0642.1)

**Comment by bnoushin7** [comment]
@kpegion 
Since the clim-751 box, links to  https://kpegion.github.io/COLA-DATASETS-CATALOG/clim_751,
it is not possible to have another nested link to "https://doi.org/10.1175/JCLI-D-16-0642.1".
Another alternative would be to have it link to "https://doi.org/10.1175/JCLI-D-16-0642.1"  after the clim_751 box. Does that sound OK?
Thank you

**Comment by kpegion** [comment]
> @kpegion
> Since the clim-751 box, links to https://kpegion.github.io/COLA-DATASETS-CATALOG/clim_751,
> it is not possible to have another nested link to "https://doi.org/10.1175/JCLI-D-16-0642.1".
> Another alternative would be to have it link to "https://doi.org/10.1175/JCLI-D-16-0642.1" after the clim_751 box. Does that sound OK?
> Thank you

Hi @bnoushin7 thanks for asking.  I suggest you skip on the link to https://doi.org/10.1175/JCLI-D-16-0642.1 for now.  If necessary, perhaps it can be added to the metadata after it is cataloged.

**Comment by bnoushin7** [comment]
@kpegion 
Thank you for your idea of adding it to the metadata. I had previously added to the bottom of the page:
https://kpegion.github.io/COLA-DATASETS-CATALOG/classes

I will change and add it to the metadata then.
