### ISSUE TITLE
CLIM 751 monthly data delete ctl directory

### ISSUE THREAD

**Issue by kpegion** [kpegion/COLA-DATASETS-CATALOG#113]
The ctl directory in the CLIM 751 monthly data can be deleted.

**Comment by bnoushin7** [comment]
Done!

**Comment by bnoushin7** [comment]
@kpegion I deleted it from the catalog but I can not delete it in COLA, it needs permission to do that.
Thank yoi

**Comment by kpegion** [comment]
Don't delete from COLA.  Just the catalog.
