### ISSUE TITLE
Catalog Datasets for CLIM680

### ISSUE THREAD

**Issue by kpegion** [kpegion/COLA-DATASETS-CATALOG#120]
Create a sub-catalog underneath classes for CLIM680 which contains the following datasets:

**[Note this issue needs more information that I will add later, but I wanted to go ahead and add the information I had for now;  Will add a comment when all information is available]**

CMIP5, piControl, tos & sos, /shared/cmip5/data/piControl/ocean/mon/Omon (need to specify files)
GPCP Global Precipitation Climate Project data set (need to specify files)
CESM, Preindustrial, /project/airsea/PMOC_PacificMultidecadalVariabilityProject/PreInd_T31_gx3v7 (need to specify files)
NOAA OLR (need to specify files and location)
Monsoon Precipitation Data over India Region, /project/mjo/for_sophia/monthly_precip_India_total.nc
Era-Interim Winds: /shared/working/rean/era-interim/daily/  (need to specify specific files)
ERA5-land:  located through ecmwf climate data store  (is this on cola?)
Arctic System Reanalysis v2, NetCDF. 3D pressure level analysis daily. Located: https://rda.ucar.edu/datasets/ds631.1/.   (probably not on cola?)

**Comment by bnoushin7** [comment]
Thank you @kpegion  for creating this issue.
Here are my questions so far:

1- Are CESM, Preindustrial two separate datasets or just one?

2- Is NOAA OLR different from ours here "https://kpegion.github.io/COLA-DATASETS-CATALOG/olr_" ?

3- The very last one (Arctic System Reanalysis v2, NetCDF. 3D pressure level analysis daily.) needs permission to download. Could you please take a look at this? https://rda.ucar.edu/datasets/ds631.1/#access

Thank you

**Comment by bnoushin7** [comment]
Done!
