### ISSUE TITLE
Catalog CMIP5 piControl Data

### ISSUE THREAD

**Issue by kpegion** [kpegion/COLA-DATASETS-CATALOG#123]
Catalog the following data:

/shared/cmip5/data/piControl/*

To the following catalog structure:

This data will go under  model->cmip5->piControl->and so on, following the directory structure of the data.

[Untitled Notebook (13).pdf](https://github.com/kpegion/COLA-DATASETS-CATALOG/files/5264098/Untitled.Notebook.13.pdf)

**Comment by bnoushin7** [comment]
@kpegion 
Would you please define their tags too?Thank you

**Comment by kpegion** [comment]
tags:  gridded,global,model,monthly or daily depending on which it is

**Comment by bnoushin7** [comment]
@kpegion Thank you for your response.
I do have some more questions:

1- You have shown monthly and daily for atmos in the pdf, but most of them have a day and month subdirectories. Could you advise me about this?

2- For seaIce, the data is located in "/shared/cmip5/data/piControl/seaIce/mon/OImon/sic", but none of them are NetCDF.

3- For the ocean, there are also subdirectories but in the end, none of them is NetCDF.

4- I have looked for the rest and they are all the same. There seems to be no NetCDF file.

**Comment by bnoushin7** [comment]
Done!
