### ISSUE TITLE
Download CMIP6 data 

### ISSUE THREAD

**Issue by kpegion** [kpegion/COLA-DATASETS-CATALOG#124]
To get the data, an example program with further explanation is located in the add_cmip branch in this repository.  It explains what data to get:

This is an example for a single model and single variable.  We need this data for the following variables:

* ua
* va
* pr

and models:

* institution: NCAR  model: CESM2
* institution: NOAA  model: GFDL-CM4
* institution: CCCMa  model: CanESM5
* institution: CAMS  model: CAMS-CSM1-0/

The example puts the data in `base_path=/scratch/kpegion/cmip6/data/`
These data need to go in `base_path=/shared/cmip6/data/` (you do not yet have write permissions to this directory, but I have requested it)

There are other files in `/shared/cmip6/data/` that should not be disturbed

You will need to install the following python packages:
intake-esm
gcsfs

**Comment by bnoushin7** [comment]
All datasets have been downloaded.
