### ISSUE TITLE
GPCP Data

### ISSUE THREAD

**Issue by kpegion** [kpegion/COLA-DATASETS-CATALOG#125]
We will now have daily and monthly GPCP data so need to make some change to cataloging this data and add the daily data.

Move /shared/obs/gridded/GPCP/precip.mon.mean.nc to /shared/obs/gridded/GPCP/monthly/precip.mon.mean.nc
Catalog this data as GPCP_monthly
tags = gridded, obs, atm, precip, monthly, global (same as before)

Copy /scratch/zmanthos/GPCP/gpcp_v01r03_daily.*.nc to /shared/obs/gridded/GPCP/daily/
Catalog this data as GPCP_daily
tags =  gridded, obs, atm, precip, daily, global

**Comment by bnoushin7** [comment]
Done.
It is working on classes and I have also updated gpcp in the cola catalog (precip subset).
