### ISSUE TITLE
OISSTv2 weekly links to wrong dataset

### ISSUE THREAD

**Issue by kpegion** [kpegion/COLA-DATASETS-CATALOG#129]
https://kpegion.github.io/COLA-DATASETS-CATALOG/sst.wkmean.1981-1989.nc

Data shown is CPC Unified Gauge-Based Analysis of Daily Precipitation over CONUS at PSD, but this data should be the OISSTv2 SSTs, not the daily CPC Precip.

**Comment by bnoushin7** [comment]
@kpegion 
Could you please check it to confirm it is alright now?
Thank you

**Comment by kpegion** [comment]
Something is still not quite right:
https://kpegion.github.io/COLA-DATASETS-CATALOG/sst.wkmean.1981-1989.nc
Still referring to CPC Unified Gauge-based analysis of precipitation when
it should be referring to weekly Optimal interpolated SST.

**Comment by bnoushin7** [comment]
Resolved
