### ISSUE TITLE
CMIP5 issues -- atm,ocn,land all have same variables

### ISSUE THREAD

**Issue by kpegion** [kpegion/COLA-DATASETS-CATALOG#198]
When I go down the subcatalogs:

model->cmip5->picontrol->[land,atmos,ocean]->day->[sub catalogs by variable name]

all variable sub catalogs are the same regardless of whether I have land, atmos, or ocean data.  I expected them to be different for the different ocean, atmos, or land variables.

**Comment by bnoushin7** [comment]
Done!
