### ISSUE TITLE
CMIP5 issues -- all models shown under sub catalog

### ISSUE THREAD

**Issue by kpegion** [kpegion/COLA-DATASETS-CATALOG#199]
If I follow the catalogs down to the model names, I get sub catalogs for all models.

model->cmip5->picontrol->land->day->mrsos->ncc.noresm1-m->r1i1p1

Sub-catalogs shown are for all models, rather than the ncc.noresm1-m model.

<img width="446" alt="Screen Shot 2020-11-05 at 3 21 10 PM" src="https://user-images.githubusercontent.com/16332933/98302938-8bfcbe00-1f7a-11eb-9218-ccace18ed3ad.png">

**Comment by bnoushin7** [comment]
Done.
