### ISSUE TITLE
Documentation of How Codes are Linked/Related/Produced

### ISSUE THREAD

**Issue by kpegion** [kpegion/COLA-DATASETS-CATALOG#2]
As I understand the codes.

The codes in _master_ are used to:
a) download the datasets
b) generate the .yaml file for each dataset
c) generate the catalog .html for each dataset

The codes in _gh-pages_ are:
a) the html that Jekyll can then display as the website.

Need to document:
a) how did the .html files in _gh-pages_ get there
b) Which ones were produced by hand?
c) Which ones were produced by scripts?

**Comment by kpegion** [comment]
I attempted to use the repository to create my own data catalog with just one dataset in it. The steps are below, along with some questions.

**Steps to Create My Own Data Catalog** 

_Get the COLA-DATASETS-CATALOG repository locally_ 

1. Clone the COLA-DATASETS-CATALOG repository 

`git clone https://github.com/kpegion/COLA-DATASETS-CATALOG.git `

2. Move into the COLA-DATASETS-CATALOG repository 

`cd COLA-DATASETS-CATALOG `

3. Switch to gh-pages branch 

`git checkout gh-pages `

 
_Create a new repository_ 

Outside of the COLA-DATASETS-CATALOG in the directory you want to use 

1. Create a new git repository 

`git init My-Datasets-Catalog `

2. Change directory to the new repository 

`cd My-Datasets-Catalog` 

3. Create and switch to the gh-pages branch 

`git checkout –b gh-pages `

- TO-DO: Create a template repository which will make it possible to merge the two main steps above 

_Get the necessary codes from COLA-DATASETS-CATALOG to my new catalog_ 

1. Copy the development-codes subdirectory from the COLA-DATASETS-CATALOG to new catalog 

`cp -r ../COLA-DATASETS-CATALOG/development-codes/ .`

2. Go into the development codes directory 

`cd development-codes `

3. Activate conda environment  

- TO-DO: I activated my datasets environment, but user should install from environment.yml and activate catalog-ing; will need to test 

4. Make run_function.sh executable 

`chmod +x run_function.sh `

5. Modify run_function.sh to point to my version of generate_catalog.py from this repository 

- TO-DO: make this automatic

6. Run the script to generate the catalog with the EN.4.2.1 dataset as a test 

`./run_function.sh `

EN4.2.1_temporary/ is now located in /homes/kpegion/pythondev/My-Datasets-Catalog/development-codes/ 

 7. Add and commit all codes in git 

8. Create and push gh-pages to a Github repository 

- What would we have to do to make easy to go from what I have here to a Data Catalog consisting of only this dataset to render on the website using gh-pages?

**Comment by bnoushin7** [comment]
Questions:
1- Why do you init a Git repo? Cloning the Git repository is enough to have all the branches.
2- There is no need to copy the development-codes subdirectory from the COLA-DATASETS-CATALOG to the new catalog if the repo is being cloned from the beginning.
@kpegion

**Comment by bnoushin7** [comment]
I will also work on automate the required steps.

**Comment by bnoushin7** [comment]
@kpegion 
You should not do "git checkout –b gh-pages" because it creates a new branch called gh-pages.
We have to just git checkout gh-pages

**Comment by bnoushin7** [comment]
I do not get the purpose of "TO-DO: Create a template repository which will make it possible to merge the two main steps above".
If we clone from the scratch, it will have everything in gh-pages branch.

**Comment by kpegion** [comment]
The goal is to be able to create a new catalog in the same style and framework as the COLA-DATASETS-CATALOG but it will contain different datasets.  
An example would be like this: https://github.com/carpentries/workshop-template

This example is a template for creating a workshop repository.   People can create many workshops using this template and customize it for the way they want without overwriting the original workshop repository.  We want the same idea for the datasets catalog where anyone can create their own datasets catalog and customize it with the datasets they want, but without changing the COLA-DATASETS-CATALOG.  

Github has a feature like this: https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository

**Comment by bnoushin7** [comment]
Done!
