### ISSUE TITLE
Change catalog references to kathy's github

### ISSUE THREAD

**Issue by kpegion** [kpegion/COLA-DATASETS-CATALOG#4]
Change all references to https://github.com/bnoushin7/COLA-DATASETS-CATALOG/blob/gh-pages/intake-catalogs/master.yaml
 to 
https://github.com/kpegion/COLA-DATASETS-CATALOG/blob/gh-pages/intake-catalogs/master.yaml

Is there a way to automate this to fill in the correct user name rather than having to do this by hand?

**Comment by bnoushin7** [comment]
Done
