### ISSUE TITLE
Name of sub-catalog and yaml file name should match

### ISSUE THREAD

**Issue by kpegion** [kpegion/COLA-DATASETS-CATALOG#42]
the name of the sub-catalog and their yaml file name should match exactly, including case.  For example, the sub-catalog is called OBS, but its .yaml file is obs.yaml.  These need to match to make it easy for users to access catalogs without knowing the internal catalog information.

**Comment by bnoushin7** [comment]
I have changed all yaml files to lower case. I was wondering if you want all the names in the webpage be lower case too?
Could you please take a look at [this](https://kpegion.github.io/COLA-DATASETS-CATALOG/sst)?
I mean, do you want all datasets like OCN or ERSSTv5 also be lowercase? Or having all the files and directory in lower case is enough? @kpegion

**Comment by kpegion** [comment]
I want to be able to do the following without errors:

```
from intake import open_catalog
import intake

catalog_name='https://raw.githubusercontent.com/kpegion/COLA-DATASETS-CATALOG/gh-pages/intake-catalogs/'

cat = open_catalog(catalog_name+'master.yaml')
list(cat)

for catalog in list(cat):
    subcat = open_catalog(catalog_name+catalog+'.yaml')

```
This give an error: 
```
Not Found for url: https://raw.githubusercontent.com/kpegion/COLA-DATASETS-CATALOG/gh-pages/intake-catalogs/OBS.yaml
```
The problem is that the names of the sub-catalogs I get when I query are:
['OBS', 'Reanalysis', 'Analysis', 'Model']
but the name of the yaml file for OBS is obs.yaml.

**Comment by bnoushin7** [comment]
Done

**Comment by kpegion** [comment]
I don't think this is solved exactly the way I intended.  I should be able to get the catalog name and open the yaml file.  For example:

```
catalog_name='https://raw.githubusercontent.com/kpegion/COLA-DATASETS-CATALOG/gh-pages/intake-catalogs/'

from intake import open_catalog
import intake
cat = open_catalog(catalog_name+'master.yaml')
list(cat)

['OBS', 'Reanalysis', 'Analysis', 'Model']

```
I get an error:
```
HTTPError: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/kpegion/COLA-DATASETS-CATALOG/gh-pages/intake-catalogs/OBS.yaml
```

The error occurs because the name of the catalog returned from open_catalog is OBS (all caps), but the name of the .yaml file is obs.yaml (all lowercase).

**Comment by bnoushin7** [comment]
@kpegion It should be solved now. Do you mind checking them out?
Thank you
