### ISSUE TITLE
Change URL label to Location

### ISSUE THREAD

**Issue by kpegion** [kpegion/COLA-DATASETS-CATALOG#46]
Example: 

<img width="1189" alt="Screen Shot 2020-07-20 at 11 29 41 AM" src="https://user-images.githubusercontent.com/16332933/87967630-563fd200-ca7c-11ea-9ac1-869e8ebb5a55.png">

Where is says URL here, change the label to say Location
Change the value to the be the location of the data on the COLA servers

For example, change:
``` 
URL https://www.psl.noaa.gov/data/gridded/data.cpc.globalprecip.html
```
to 

```
Location /shared/obs/gridded/CPC-PRECIP/
```

**Comment by bnoushin7** [comment]
Done
