### ISSUE TITLE
Yaml files having trouble being read by intake

### ISSUE THREAD

**Issue by bnoushin7** [kpegion/COLA-DATASETS-CATALOG#68]
ersstv4
ersstv5
hadisst
sst
aviso
legates
cpc-precip

**Comment by bnoushin7** [comment]
legates --> Done

**Comment by bnoushin7** [comment]
ersstv4 Done
ersstv5 Done

**Comment by bnoushin7** [comment]
hadisst Done

**Comment by bnoushin7** [comment]
sst Done!

**Comment by bnoushin7** [comment]
There are only issues with aviso and cpc-precip

**Comment by bnoushin7** [comment]
@kpegion 
 I want to read cpc files with commands below:
from intake import open_catalog

cat = open_catalog("https://raw.githubusercontent.com/kpegion/COLA-DATASETS-CATALOG/gh-pages/intake-catalogs/cpc-precip.yaml")
ds = cat.netcdf.read()
ds

And here is the memory error I am getting:

"MemoryError: Unable to allocate 14.6 GiB for an array with shape (15114, 360, 720) and data type float32"

Any suggestion?

**Comment by bnoushin7** [comment]
@kpegion I checked and i guess the cola6 and cola7 have 16 GB memory, is that correct?

**Comment by bnoushin7** [comment]
@kpegion 
Here is the issue with Aviso:
MemoryError: Unable to allocate 485. MiB for an array with shape (365, 121, 1440) and data type float64

**Comment by kpegion** [comment]
There's a way to read in the metadata without using the memory to read in all the data.   I'll post a code snippet sometime today.

**Comment by kpegion** [comment]
I think something like this will solve the memory issue.  

```
import intake
url='https://raw.githubusercontent.com/kpegion/COLA-DATASETS-CATALOG/gh-pages/intake-catalogs/precip.yaml'

cat = intake.open_catalog(url)
ds=cat['cpc-precip'].to_dask()
ds

```

**Comment by bnoushin7** [comment]
Thank you. Solved!
