### ISSUE TITLE
Check if intake.gui is useful for us.

### ISSUE THREAD

**Issue by bnoushin7** [kpegion/COLA-DATASETS-CATALOG#89]
Please check out the notebook (/homes/nbehboud/intake_gui.ipynb) to see if the GUI feature is helpful for us.

**Comment by bnoushin7** [comment]
@kpegion

**Comment by kpegion** [comment]
your home directory is locked, so I can't access the notebook

**Comment by bnoushin7** [comment]
@kpegion Shall I put it in another place? I am not sure why my home is locked

**Comment by kpegion** [comment]
you can change the permissions on your home directory.  It defaults closed to everyone.

**Comment by bnoushin7** [comment]
I did, Could you check it now please?

**Comment by kpegion** [comment]
For now, I am not too excited about the GUI. It doesn't work well for me (freezes up often when I press the + button) and I am not sure I see how it will help us. Most of our users are not big fans of GUIs anyway.  Maybe leave this open to consider in the future if there is a way it may be useful for us.

**Comment by bnoushin7** [comment]
Done!
