### ISSUE TITLE
Remove use of word master throughout catalog

### ISSUE THREAD

**Issue by kpegion** [kpegion/COLA-DATASETS-CATALOG#92]
There is a widespread effort around diversity, inclusion, equity and justice in computer science to remove the use of the word `master` as it is a reference to masters and slaves.   

Change `Browse Master Catalog` to `Browse Catalog`
Change `master.yaml` to `main.yaml` and other any other references to `master` to `main`.

**Comment by bnoushin7** [comment]
Done!
