### ISSUE TITLE
Add Date last updated to Metadata

### ISSUE THREAD

**Issue by kpegion** [kpegion/COLA-DATASETS-CATALOG#93]
Is it possible to indicate the date that the dataset was last updated based on file dates under Metadata?  

I expect this to be possible and relatively easy for data on COLA servers.  Probably more difficult for remote datasets.

**Comment by bnoushin7** [comment]
@kpegion 
That is a great idea!
Here is my question: is it something that should have been present in the YAML file? 
Some of the remote datasets have something similar in their YAML file like:
date_created, date_modified, create_date, creation_date. But just a few of them include this information. 
I did not find anything similar in the local YAML files. But for local datasets, I think ```stat``` commands works.

For instance, for the files in ```/project/airsea/AVISO/```, if I do stat in one of the files, here is what I get:

**Comment by bnoushin7** [comment]
```stat 2015_15N-15S_dataset-duacs-rep-global-merged-allsat                                                                                                                      -phy-l4-v3_SLA_ADT.nc
  File: ‘2015_15N-15S_dataset-duacs-rep-global-merged-allsat-phy-l4-v3_SLA_ADT.n                                                                                                                      c’
  Size: 508793428       Blocks: 649722     IO Block: 1048576 regular file
Device: 27h/39d Inode: 40557       Links: 1
Access: (0644/-rw-r--r--)  Uid: (  810/kturne15)   Gid: (  100/   users)
Access: 2020-08-05 13:46:54.705075937 -0400
Modify: 2017-04-22 11:44:11.000000000 -0400
Change: 2018-05-01 20:05:22.565726712 -0400
 Birth: -
```

**Comment by kpegion** [comment]
I'm looking for the date of the most recently updated file so for example:
```
ls -ltr /project/airsea/AVISO/
```
The date of the last changed file is: Aug 29  2017 

This is different than what I get from stat of that directory, although I am not sure why.

stat /project/airsea/AVISO/

File: ‘/project/airsea/AVISO/’
 Size: 26        	Blocks: 141        IO Block: 4096   directory
Device: 35h/53d	Inode: 37826       Links: 2
Access: (0755/drwxr-xr-x)  Uid: (  810/kturne15)   Gid: (  100/   users)
Access: 2020-08-28 13:57:00.607727321 -0400
Modify: 2017-09-08 12:36:46.000000000 -0400
Change: 2018-05-01 20:05:22.565726712 -0400
 Birth: -

```

**Comment by bnoushin7** [comment]
@kpegion 
Is  "Modify" not giving the same information?

**Comment by kpegion** [comment]
Modify gives Aug 9, 2017; ls gives Aug 29, 2017.  Not sure why. I may have overlooked something. I am trying to do too many things at one time :-)

**Comment by bnoushin7** [comment]
@kpegion I just checked, you are 100% right. I will try to figure out a way for it. Thank you

**Comment by bnoushin7** [comment]
Done!
