### ISSUE TITLE
Search bar is not appearing

### ISSUE THREAD

**Issue by kpegion** [kpegion/COLA-DATASETS-CATALOG#94]
I see the text telling me I can enter tags in the search bar, but I don't see the search bar. 

<img width="1153" alt="Screen Shot 2020-08-25 at 2 56 46 PM" src="https://user-images.githubusercontent.com/16332933/91227109-35a21200-e6e3-11ea-8c52-6b3eb5708c45.png">

**Comment by bnoushin7** [comment]
I am redesigning the search by tag. Will correct it soon.

**Comment by bnoushin7** [comment]
Done!
